### ISSUE TITLE
hexo g  报语法错误

### ISSUE THREAD

**Issue by hosxy** [neoFelhz/hexo-theme-spectre#3]
**I certify that I have first consulted** (check with "x")

**我确认我已经查看了** (选择时请使用 "x" 取代方括号中的空格)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Spectre theme issues | Spectre 主题的其它 issue](https://github.com/neoFelhz/hexo-theme-spectre/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

## 我正在申请  (选择时请使用 "x" 取代方括号中的空格)

- [x] bug report | 反馈一个 Bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

----

### Node.js 和 NPM 的相关信息

    node --version
    v10.6.0

    npm --version
    6.1.0

### 依赖包相关信息

    {
      "name": "hexo-site",
      "version": "0.0.0",
      "private": true,
      "hexo": {
       "version": ""
     },
      "dependencies": {
       "hexo": "^3.2.0",
       "hexo-generator-archive": "^0.1.4",
       "hexo-generator-category": "^0.1.3",
       "hexo-generator-index": "^0.2.0",
       "hexo-generator-tag": "^0.2.0",
       "hexo-renderer-ejs": "^0.3.0",
       "hexo-renderer-stylus": "^0.3.1",
       "hexo-renderer-marked": "^0.3.0",
       "hexo-server": "^0.2.0"
      }
     }

### Hexo 版本号

     hexo --version
     hexo: 3.7.1
     hexo-cli: 1.1.0
     os: Linux 4.4.0-112-generic linux x64
     http_parser: 2.8.0
     node: 10.6.0
     v8: 6.7.288.46-node.13
     uv: 1.21.0
     zlib: 1.2.11
     ares: 1.14.0
     modules: 64
     nghttp2: 1.32.0
     napi: 3
     openssl: 1.1.0h
     icu: 61.1
     unicode: 10.0
     cldr: 33.0
     tz: 2018c

### 站点配置文件和主题配置文件

    # Site
    title: hosxy
    subtitle:
    description:
    keywords:
    author: hosxy
    language: zh-CN
    timezone:

### 报错日志

    INFO  Start processing
    ERROR Process failed: layout/_partial/index/author_info.ejs
    SyntaxError: Unexpected token =            in /home/travis/build/hosxy/hosxy.github.io/themes/spectre/layout/_partial/index/author_info.ejs while   compiling ejs
    If the above error is not helpful, you may want to try EJS-Lint:

    https://github.com/RyanZim/EJS-Lint Or, if you meant to create an async function, pass async: true as an option.
    at new Function (<anonymous>)
    at Template.compile (/home/travis/build/hosxy/hosxy.github.io/node_modules/ejs/lib/ejs.js:618:12)

    at Object.compile (/home/travis/build/hosxy/hosxy.github.io/node_modules/ejs/lib/ejs.js:389:16)

    at Function.ejsRenderer.compile (/home/travis/build/hosxy/hosxy.github.io/node_modules/hexo-renderer-ejs/lib/renderer.js:11:14)

    at Theme._View.View.View._precompile (/home/travis/build/hosxy/hosxy.github.io/node_modules/hexo/lib/theme/view.js:117:31)

    at Theme._View.View.View (/home/travis/build/hosxy/hosxy.github.io/node_modules/hexo/lib/theme/view.js:13:8)

    at new Theme._View.View (/home/travis/build/hosxy/hosxy.github.io/node_modules/hexo/lib/theme/index.js:37:10)

    at Theme.setView (/home/travis/build/hosxy/hosxy.github.io/node_modules/hexo/lib/theme/index.js:71:20)

    at file.read.then.result (/home/travis/build/hosxy/hosxy.github.io/node_modules/hexo/lib/theme/processors/view.js:14:14)

    at tryCatcher (/home/travis/build/hosxy/hosxy.github.io/node_modules/bluebird/js/release/util.js:16:23)

    at Promise._settlePromiseFromHandler (/home/travis/build/hosxy/hosxy.github.io/node_modules/bluebird/js/release/promise.js:512:31)

    at Promise._settlePromise (/home/travis/build/hosxy/hosxy.github.io/node_modules/bluebird/js/release/promise.js:569:18)

    at Promise._settlePromise0 (/home/travis/build/hosxy/hosxy.github.io/node_modules/bluebird/js/release/promise.js:614:10)

    at Promise._settlePromises (/home/travis/build/hosxy/hosxy.github.io/node_modules/bluebird/js/release/promise.js:693:18)

    at Promise._fulfill (/home/travis/build/hosxy/hosxy.github.io/node_modules/bluebird/js/release/promise.js:638:18)

    at Promise._resolveCallback (/home/travis/build/hosxy/hosxy.github.io/node_modules/bluebird/js/release/promise.js:432:57)
----

### 预期结果和你的实际结果

----

**Comment by invom** [comment]
`layout/_partial/index/author_info.ejs`的11行，将`theme.search.use === true`改为`theme.search.use === true`
我是这么改的，仅供参考

**Comment by rickyxume** [comment]
我也遇到了这个问题。按照楼上的操作还是不行啊。，。

**Comment by invom** [comment]
@rickyxume 是不是后面还有一个ejs的正则表达式报错 ？哈哈我也没解决

**Comment by liwuxi** [comment]
作者说有时间就重构，我的解决方案是直接copy作者blog里的主题文件。

**Comment by SuperNG6** [comment]
确实是，在最新版的hexo里已经没有办法运行了，这个主题真的很好看，停止维护真是太可惜了
